# Generated by Django 3.1.5 on 2023-06-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Буква',
                'verbose_name_plural': 'Буквы',
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание вида страхования')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид страхования',
                'verbose_name_plural': 'Виды страхования',
                'ordering': ['cat_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('letter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.letters', verbose_name='Начальная буква')),
            ],
            options={
                'verbose_name': 'Филлиал',
                'verbose_name_plural': 'Филлиалы',
                'ordering': ['letter_id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.insurancecompany', verbose_name='Филиал работника')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('accept_terms', models.BooleanField(default=True, verbose_name='Согласие с условиями договора')),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Первоначальный взнос')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.insurancecompany', verbose_name='Филиал работника')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.insurancetype', verbose_name='Вид страхования')),
                ('ins_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.insuranceobjects', verbose_name='Объект страхования')),
            ],
        ),
    ]
