# Generated by Django 3.1.5 on 2023-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230603_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
