# Generated by Django 4.2.1 on 2023-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='insuranceagent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуг'),
        ),
        migrations.AddField(
            model_name='insuranceagent',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images/agent', verbose_name='Фото'),
        ),
    ]
