# Generated by Django 4.2.1 on 2023-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_coupons_vacancy_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceagent',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Доход'),
        ),
    ]
